// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4I7kXbiqyuYFTubpLB-OPbCCkLzyxbA',
    appId: '1:406841665431:web:f04abd10bf9c0e26dc06d2',
    messagingSenderId: '406841665431',
    projectId: 'automatic-door-49483',
    authDomain: 'automatic-door-49483.firebaseapp.com',
    storageBucket: 'automatic-door-49483.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwADUMy_BUAZ2u8LpG3u7RnMrUTk-a8s',
    appId: '1:406841665431:android:d978a9a4a70c166fdc06d2',
    messagingSenderId: '406841665431',
    projectId: 'automatic-door-49483',
    storageBucket: 'automatic-door-49483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMMAmGUYi73Hf5xxuGxg0iJLBjU0oqdYk',
    appId: '1:406841665431:ios:dbbc90e8d4619401dc06d2',
    messagingSenderId: '406841665431',
    projectId: 'automatic-door-49483',
    storageBucket: 'automatic-door-49483.firebasestorage.app',
    iosBundleId: 'com.example.smartIotParkingLotSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMMAmGUYi73Hf5xxuGxg0iJLBjU0oqdYk',
    appId: '1:406841665431:ios:dbbc90e8d4619401dc06d2',
    messagingSenderId: '406841665431',
    projectId: 'automatic-door-49483',
    storageBucket: 'automatic-door-49483.firebasestorage.app',
    iosBundleId: 'com.example.smartIotParkingLotSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX4I7kXbiqyuYFTubpLB-OPbCCkLzyxbA',
    appId: '1:406841665431:web:d60b32b8216d4a82dc06d2',
    messagingSenderId: '406841665431',
    projectId: 'automatic-door-49483',
    authDomain: 'automatic-door-49483.firebaseapp.com',
    storageBucket: 'automatic-door-49483.firebasestorage.app',
  );
}
